version: '2'

services:

  postgres:
    image: postgres:15
    expose:
      - 5432
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: ubuntu
      POSTGRES_DB: messengerapp
    volumes:
      - data:/var/lib/postgresql/data

  webservice-1.0:
    image: webservice-1.0
    expose:
      - 8080
    ports:
      - "8080:8080"

volumes:
  data: {}
