version: '2'

services:

  postgres:
    image: postgres:15
    expose:
      - 5432
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_PASSWORD: ubuntu
      POSTGRES_DB: messengerapp
    # neues, leeres Volume erstellen, in dem der Inhalt
    # des Container-VZs "/var/lib/postgres/data" auf dem Hostgerät gespeichert wird.
    volumes:
      - data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  webservice-1.0:
    image: webservice-1.0
    expose:
      - 8080
    ports:
      - "8080:8080"

volumes:
  data: {}

